# Config file for automatic testing at travis-ci.org

language: python

cache: pip

python:
    - 3.6

install:
    - pip install -U pipenv
    - pipenv install --dev --ignore-pipfile

script:
    - make test-all
